branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: aperture
  branch: null
  default_ec2_keyname: aperture
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
